using System.Collections.Generic;
using UnityEngine;

namespace Platformer.Survival
{
    /// <summary>Pivot (feet) of every painted runner prop in Resources/Runner. Generated by the offline painter.</summary>
    public static class RunnerPropPivots
    {
        public static readonly Dictionary<string, Vector2> All = new()
        {
            ["prop_banner_0"] = new Vector2(0.4904f, 0.0556f),
            ["prop_banner_1"] = new Vector2(0.4904f, 0.0556f),
            ["prop_brazier"] = new Vector2(0.5f, 0.1063f),
            ["prop_burnt_0"] = new Vector2(0.4982f, 0.0415f),
            ["prop_burnt_1"] = new Vector2(0.4977f, 0.0415f),
            ["prop_bush_0"] = new Vector2(0.5f, 0.1483f),
            ["prop_bush_1"] = new Vector2(0.4946f, 0.1483f),
            ["prop_bush_2"] = new Vector2(0.4913f, 0.1483f),
            ["prop_bush_3"] = new Vector2(0.497f, 0.1483f),
            ["prop_crate_0"] = new Vector2(0.4866f, 0.1875f),
            ["prop_crate_1"] = new Vector2(0.4891f, 0.1875f),
            ["prop_crenel"] = new Vector2(0.4961f, 0.0f),
            ["prop_deadtree_0"] = new Vector2(0.5f, 0.0415f),
            ["prop_deadtree_1"] = new Vector2(0.4983f, 0.0415f),
            ["prop_fence"] = new Vector2(0.4966f, 0.1875f),
            ["prop_grave_0"] = new Vector2(0.4929f, 0.1063f),
            ["prop_grave_1"] = new Vector2(0.4929f, 0.1063f),
            ["prop_grave_2"] = new Vector2(0.4929f, 0.1063f),
            ["prop_ironfence"] = new Vector2(0.4942f, 0.125f),
            ["prop_lantern_0"] = new Vector2(0.4844f, 0.0927f),
            ["prop_lantern_1"] = new Vector2(0.4844f, 0.0927f),
            ["prop_maple_0_0"] = new Vector2(0.4961f, 0.0426f),
            ["prop_maple_0_1"] = new Vector2(0.4966f, 0.0365f),
            ["prop_maple_1_0"] = new Vector2(0.4975f, 0.0426f),
            ["prop_maple_1_1"] = new Vector2(0.4967f, 0.0365f),
            ["prop_maple_2_0"] = new Vector2(0.4986f, 0.0426f),
            ["prop_maple_2_1"] = new Vector2(0.4977f, 0.0365f),
            ["prop_maple_3_0"] = new Vector2(0.4973f, 0.0426f),
            ["prop_maple_3_1"] = new Vector2(0.4966f, 0.0365f),
            ["prop_pine_0"] = new Vector2(0.4965f, 0.04f),
            ["prop_pine_1"] = new Vector2(0.4971f, 0.0333f),
            ["prop_rock_0"] = new Vector2(0.4886f, 0.1635f),
            ["prop_rock_1"] = new Vector2(0.4913f, 0.1635f),
            ["prop_rock_2"] = new Vector2(0.5f, 0.1635f),
            ["prop_ruin_0"] = new Vector2(0.4989f, 0.0532f),
            ["prop_ruin_1"] = new Vector2(0.4977f, 0.0532f),
            ["prop_stump"] = new Vector2(0.4938f, 0.2452f)
        };
    }
}
